#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/camera/lexus/blobs

PRODUCT_COPY_FILES += \
    vendor/oplus/camera/lexus/blobs/proprietary/odm/etc/camera/license_release_fdc.lic:$(TARGET_COPY_OUT_ODM)/etc/camera/license_release_fdc.lic \
    vendor/oplus/camera/lexus/blobs/proprietary/odm/etc/camera/model/license.lic:$(TARGET_COPY_OUT_ODM)/etc/camera/model/license.lic \
    vendor/oplus/camera/lexus/blobs/proprietary/odm/etc/camera/singleblur/license_release.license:$(TARGET_COPY_OUT_ODM)/etc/camera/singleblur/license_release.license \
    vendor/oplus/camera/lexus/blobs/proprietary/product/etc/camera/engineer_camera_config.json:$(TARGET_COPY_OUT_PRODUCT)/etc/camera/engineer_camera_config.json \
    vendor/oplus/camera/lexus/blobs/proprietary/system/etc/permissions/privapp-permissions-oplus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-oplus.xml \
    vendor/oplus/camera/lexus/blobs/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/chre_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/chre_dynamic_sensors.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_flight_md.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_flight_md.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_psd_disable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_disable.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_psd_enable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_enable.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm3b68v04s12n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b68v04s12n53.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm3b73v04s12n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm3b73v04s12n50.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a68v08s12n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a68v08s12n52.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a68v08s12n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a68v08s12n53.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n02.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n02.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n03.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n03.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n04.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n06.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n06.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n07.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n07.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n12.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n12.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n13.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n13.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n14.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n14.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n15.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n15.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n16.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n16.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n17.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n17.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n18.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n18.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n19.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n19.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n20.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n20.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n21.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n21.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n22.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n22.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n23.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n23.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n24.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n24.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n25.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n25.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n26.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n26.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n27.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n27.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n28.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n28.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n29.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n29.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n30.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n30.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n35.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n35.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n36.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n36.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n37.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n37.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n38.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n38.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n39.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n39.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n40.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n43.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n43.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n44.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n44.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n45.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n45.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n46.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n46.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n47.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n47.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n48.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n48.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n49.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n49.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n50.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n51.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n51.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n54.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n54.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n55.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n55.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n56.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n56.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n57.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n57.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n58.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n58.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n59.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n59.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n60.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n60.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n61.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n61.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/bm4a73v08s12n62.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm4a73v08s12n62.bin \
    vendor/oplus/camera/lexus/blobs/proprietary/vendor/lib64/libpnc_cl_program.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/libpnc_cl_program.bin

PRODUCT_PACKAGES += \
    vendor.oplus.hardware.cameraextension@1.0 \
    libiccprofile \
    libpenguin \
    libAPSClient-alog-jni \
    libAPSClient-cmd-jni-extension.oplus \
    libAPSClient-cmd-jni \
    libAPSClient-jni \
    libAncFilter_jni \
    libAncHumBokeh-jni \
    libAncHumanDoubleExposure-jni \
    libAncHumanRetain-jni_v2 \
    libAncHumanSegFigureFusion-jni \
    libAncHumanVideo-jni \
    libApsFaceBeautyPreviewProductJni \
    libApsSuperEISPreviewJni \
    libAvatarEngineRender \
    libAvatarEngineRenderNative \
    libCombineLut \
    libCombineLutJni \
    libFileExtender-jni \
    libHeifEncoderWrapper \
    libHeifWinBufExchg-jni \
    libMsEffectSdk \
    libNativeWinBuffExchange \
    libOplusBlurPreviewJNI \
    libOplusStringJNI-extension.oplus \
    libOplusStringJNI \
    libSuperTextWrapper_system_ext \
    libXDocProcessSDK-jni \
    libXDocProcessSDK_system_ext \
    libYTCommon_system_ext \
    libapssuspend-jni.oplus \
    libarcsoft_panorama_burstcapture \
    libarcsoft_wideselfie \
    libbinauralrenderer_wrapper.qti \
    libbsproxy \
    libcsextimpl \
    libextendfile_system_ext \
    libhoaeffects.qti \
    libhoaeffects_csim \
    libjni_burstpmk \
    libjni_wideselfie \
    libjnisingleblur_api \
    libjnistblur_api \
    liblivephoto.frc.jni \
    libmpbase_system_ext \
    liboplus-uah-client_system_ext \
    liboplusheifwriter \
    liboplushwui_jni \
    libortc_so.oplus \
    libsatellite_audio_jni.oplus \
    libsingle_camera_bokeh2_native \
    libsingle_camera_bokeh_native \
    libsoundtouch.oplus \
    libsoundtouch_jni.oplus \
    libst_mobile \
    libst_sticker_jni \
    libsuperNight.oplus \
    libvr_amb_engine \
    vendor.oplus.hardware.cameraMDM@1.0 \
    libOplusSecurity \
    ExtensionsService \
    OplusAppPlatform \
    OplusCamera \
    OppoGallery2 \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk
